server:
  port: 8767

spring:
  application:
    name: zuul-server


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

  instance:
    preferIpAddress: true


zuul:
  routes:
    first-client:
      serviceId: first-client

